LoadPath = 'config.toml'
Address = 'localhost:1234'
ServicesPath = 'services'
Secret = 'secret'

[Services.htest]
Repo = 'https://github.com/s1adem4n/htest.git'
Exec = 'build/htest'
Build = 'go mod vendor && go build -o build/htest'
Restart = false
MaxRestarts = 0
Secret = 'verysecretgithubwebhooksecret'

[Services.htest.Proxy]
Match = '192.168.1.100'
Upstream = 'localhost:8080'
