address = ":1234"
servicesPath = "services"

[[services]]
name = "htest"
repo = "https://github.com/s1adem4n/htest.git"
exec = "build/htest"
build = "go mod vendor && go build -o build/htest"
restart = true
maxRestarts = 5
secret = "verysecretgithubwebhooksecret"
[services.proxy]
address = "localhost:8080"
upstream = "192.168.1.100"
